### PR TITLE
I made it to html with table

### PR DESCRIPTION
**Pull request by Helloyunho**

### CODE REVIEW

**Comment by Danue1** [comment]
Use tbody and thead to rewrite it. Is it possible?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#More_Examples

**Comment by Helloyunho** [comment]
Yea I can do it

**Comment by Danue1** [comment]
I'll be looking forward to it.

**Comment by Danue1** [comment]
I'd like to add a blank line to the last line. Is it okay?

**Comment by Helloyunho** [comment]
Yes it's ok Actually I forgot to add a blank at the last

**Pull request merged**
